import numpy as np
import xarray as xr
import pandas as pd
import warnings
from tempfile import NamedTemporaryFile
import json

from agage_archive.config import open_data_file, data_file_path
from agage_archive.run import run_individual_instrument
from agage_archive.formatting import format_attributes
from agage_archive.formatting import format_variables
from agage_archive.formatting import prefix_instrument_type


def check_cf_compliance(dataset):
    """Tests the CF compliance of a dataset when written to netCDF format.
    Taken from openghg/tests/helpers/cfchecking.py module

    Args: 
        dataset: An xarray.Dataset
    Returns:
        bool: True if compliant
    """
    from cfchecker.cfchecks import CFChecker

    checker = CFChecker(debug=False, version="1.8")

    catch_errors_warnings = False

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        with NamedTemporaryFile(suffix=".nc") as tmpfile:
            dataset.to_netcdf(tmpfile.name)
            result = checker.checker(file=tmpfile.name)

            if result["global"]["FATAL"] or result["global"]["ERROR"]:
                catch_errors_warnings = True

            for var in result["variables"].keys():            
                if result["variables"][var]["FATAL"] or result["variables"][var]["ERROR"]:
                    catch_errors_warnings = True

    if catch_errors_warnings:
        return False
    else:
        return True


def test_variable_schema():
    with open(data_file_path("variables.json", this_repo=True)) as f:
        variables = json.load(f)

    valid_optional = {"True", "False"}
    valid_remove_flagged = {"True", "False", "Zero"}
    valid_resample_methods = {"", "first", "mean", "median", "mode", "sum", "standard_error"}
    valid_dtypes = {"f4", "f8", "i4", "i2", "i8", "i1", "u1", "u2", "u4", "u8", "S1"}

    for variable, definition in variables.items():
        assert definition["optional"] in valid_optional, variable
        if "remove_flagged" in definition:
            assert definition["remove_flagged"] in valid_remove_flagged, variable
        assert definition["encoding"]["dtype"] in valid_dtypes, variable
        if "resample_method" in definition:
            assert definition["resample_method"] in valid_resample_methods, variable


def test_format_variables_restores_warning_filters():
    ds = xr.Dataset(
        {"mf": ("time", np.array([1.0]))},
        coords={"time": pd.date_range("2021-01-01", periods=1)},
        attrs={"network": "agage_test", "species": "nf3", "calibration_scale": "SIO-05"},
    )
    ds["mf"].attrs["units"] = "1e-9"
    with open_data_file("variables.json", this_repo=True) as f:
        variables = json.load(f)
    translation = {
        variable: "mf"
        for variable, definition in variables.items()
        if variable != "time" and definition["optional"] == "False"
    }
    original_filters = warnings.filters[:]

    try:
        format_variables(ds, variable_translate=translation)
    finally:
        assert warnings.filters == original_filters


def test_cf_compliance(clean_output):
    """Test CF compliance of the NF3 MHD dataset, which is generated by the run_single_site function on the agage-test data

    Args:
        clean_output: Fixture emptying the agage_test output directory before and after.

    """

    network = 'agage_test'
    sub_path = 'output'
    instrument = "GCMS-Medusa"
    site = "MHD" # data_release_schedule modified so that this is the only site
    species = "nf3"

    # Get current version number from attributes.json
    with open_data_file("attributes.json", network=network) as f:
        attributes = json.load(f)
    version = attributes["version"]

    run_individual_instrument(network=network,
                    instrument=instrument,
                    species=[species],
                    monthly=False,
                    verbose=False)
    
    with open_data_file(filename=f'{network.lower()}-{instrument.lower()}_{site.lower()}_{species}_{version}.nc',
                        network=network,
                        sub_path=sub_path + '/nf3/individual-instruments',
                        ) as f:
        ds = xr.load_dataset(f)

    assert check_cf_compliance(dataset=ds) == True


def test_format_attributes():
    # Test that the attributes are formatted correctly

    # Test dataset
    data = {
        "time": pd.date_range(start="2021-01-01 00:00", periods=10, freq="D"),
        "data": np.random.random(10),
    }

    ds = xr.Dataset(data_vars={"mf": (["time"], data["data"])}, coords={"time": data["time"]})

    ds.attrs["site_code"] = "CBW"
    ds.attrs["calibration_scale"] = "SIO-05"

    # Test attributes
    ds = format_attributes(ds,
                           network="agage_test",
                           site="CBW",
                           species="nf3",
                           extra_attributes={"product_type": "mole_fraction",
                                             "frequency": "high-frequency",
                                             "instrument_selection": "test"},
                           )
    
    assert ds.attrs["site_code"] == "CBW"
    assert ds.attrs["species"] == "nf3"
    assert ds.attrs["network"] == "agage_test"
    assert ds.attrs["start_date"] == "2021-01-01 00:00:00"
    assert ds.attrs["end_date"] == "2021-01-10 00:00:00"
    assert ds.attrs["product_type"] == "mole_fraction"
    assert ds.attrs["frequency"] == "high-frequency"
    assert ds.attrs["instrument_selection"] == "test"
    assert ds.attrs["version"] == "testv1"


def test_prefix_instrument_type():
    """Instrument identifiers are prefixed with their type where that adds info (#148)."""

    # An opaque identifier gains its type, using the " - " separator from the issue
    assert prefix_instrument_type("agilent_5975", "GCMS-Medusa") == "GCMS-Medusa - agilent_5975"
    # An identifier equal to its type is left unchanged (no "GCMD - GCMD")
    assert prefix_instrument_type("GCMD", "GCMD") == "GCMD"
    # An identifier already beginning with its type is left unchanged
    assert prefix_instrument_type("GAGE_GCMD", "GAGE") == "GAGE_GCMD"
    assert prefix_instrument_type("GCMS-ADS", "GCMS-ADS") == "GCMS-ADS"
    # No type available: return the identifier untouched
    assert prefix_instrument_type("agilent_5975", "") == "agilent_5975"
